### ISSUE TITLE
Category Archives unexpected behavior

### ISSUE THREAD

**Issue by dws122** [maithemewp/mai-publisher#4]
tested on TPM and DWCL

settings as
<img width="729" alt="Screenshot 2023-10-05 at 12 45 28 PM" src="https://github.com/maithemewp/mai-publisher/assets/12969150/56a264be-1333-421a-92f1-dec36c843ea9">

display as
<img width="1080" alt="Screenshot 2023-10-05 at 12 46 26 PM" src="https://github.com/maithemewp/mai-publisher/assets/12969150/995a0e18-d528-4806-929e-3c32faa825ca">

**Comment by JiveDig** [comment]
Actually, this brings up a tricky scenario. The in-entries location is responsive, in that it's displayed by "rows".

Imagine this scenario:
- Blog archive is set to show 9 posts in 3 columns.
- That's **3 rows of 3 on desktop**.
- That's **5 rows of 2 on tablet** (the last row will only have 1 entry in the row, but it's still a row).
- That's **9 rows of 1 on mobile** (stacked).

If we set the ad to show after 1, 4, 7 rows here is what happens:
- Mobile: It will show after the 1st, 4th, and 7th _post_.
- Tablet: It will show after the 1st _row_ of 2, 4th _row_ of 2, then after the 5th _row_ of 2 since that's the last one.
- Desktop: It will show after the 1st _row_, then twice after the 3rd _row_ since that's the last row.

We have potential for a bunch of back to back ads to show up doing it this way.

I'm thinking the logic should be that it only gets added in between rows (not after the last one) on desktop. Mobile will be whatever it is, tablet the same, and we'll never have back to back ads on any device.

I'm going to make it work that way now. @dws122 if you want to discuss/change, let's discuss.
